var str = '';

str +='<div class="pcContents">';
str +='  <h1 class="pch1"><img src="../../public/image/pc/logo_sejong.png" alt="세종엔" /></h1>';
str +='  <h2 class="pch2">1등 스마트도시<br />세종특별자치시 <br />세종에는요~</h2>';
str +='  <div class="pcInfomation recentService ">';
str +='    <h3 class="pch3">이용이 많은 정보</h3>';
str +='<nav class="homeNav">';
str +='  <div class="slideContainer">';
str +='    <ul class="swiper-wrapper">';
str +='      <li class="swiper-slide">';
str +='        <a href="#">';
str +='          <b class="poa">1</b>';
str +='          <div class="roundBox">';
str +='            <b class="text">여민전/상생플러스</b>';
str +='            <div class="textGroup">';
str +='            <img src="../../public/image/common/ico24_fill/@2x/ico_24_24store_filled.png" alt="">';
str +='              <span class="subText">무인민원발급기</span>';
str +='            </div>';
str +='          </div>';
str +='        </a>';
str +='      </li>';
str +='      <li class="swiper-slide">';
str +='        <a href="#">';
str +='          <b class="poa">2</b>';
str +='          <div class="roundBox">';
str +='            <b class="text">안전신고</b>';
str +='            <div class="textGroup">';
str +='            <img src="../../public/image/common/ico24_fill/@2x/ico_24_light_filled.png" alt="">';
str +='              <span class="subText">안전</span>';
str +='            </div>';
str +='          </div>';
str +='        </a>';
str +='      </li>';
str +='      <li class="swiper-slide">';
str +='        <a href="#">';
str +='          <b class="poa">3</b>';
str +='          <div class="roundBox">';
str +='            <b class="text">우리가게</b>';
str +='            <div class="textGroup">';
str +='            <img src="../../public/image/common/ico24_fill/@2x/ico_24_carehouse_filled.png" alt="">';
str +='              <span class="subText">소통</span>';
str +='            </div>';
str +='          </div>';
str +='        </a>';
str +='      </li>';
str +='      <li class="swiper-slide">';
str +='        <a href="#">';
str +='          <b class="poa">4</b>';
str +='          <div class="roundBox">';
str +='            <b class="text">어울링</b>';
str +='            <div class="textGroup">';
str +='            <img src="../../public/image/common/ico24_fill/@2x/ico_24_management_filled.png" alt="">';
str +='              <span class="subText">교통</span>';
str +='            </div>';
str +='          </div>';
str +='        </a>';
str +='      </li>';
str +='    </ul>';
str +='  </div>';
str +='</nav>';
str +='  </div>';
str +='  <div class="pcApp">';
str +='    <h3 class="pch3">이제, 앱으로 편하게 생활해요</h3>';
str +='    <div class="links">';
str +='      <a href="#" target="_blank"><img src="../../public/image/pc/ico_android.png" alt="안드로이드 앱" /></a>';
str +='      <a href="#" target="_blank"><img src="../../public/image/pc/ico_ios.png" alt="IOS 앱" /></a>';
str +='    </div>';
str +='  </div>';
str +='</div>';
str +='<div class="pcDeco poa1"></div>';
str +='<div class="pcDeco poa2"></div>';
str +='<div class="pcDeco poa3"></div>';
str +='<div class="pcDeco poa4"></div>';
str +='<div class="pcDeco poa5"></div>';
str +='<div class="pcDeco poa6"></div>';
str +='<div class="pcDeco poa7"></div>';
str +='<div class="pcDeco poa8"></div>';

document.write(str);


