var str = '';

str +='<div class="pcContents">';
str +='  <h1 class="pch1"><img src="../../public/image/pc/logo_sejong.png" alt="세종엔" /></h1>';
str +='  <h2 class="pch2">1등 스마트도시<br />세종특별자치시 <br />세종에는요~</h2>';
str +='  <div class="pcInfomation">';
str +='    <h3 class="pch3">이용이 많은 정보</h3>';
str +='    <ul>';
str +='      <li>';
str +='        <a href="#"><span class="roundBox"><img src="../../public/image/common/ico24_fill/@2x/ico_24_24store_filled.png" alt=""></span><p>무인민원발급기</p></a>';
str +='      </li>';
str +='      <li>';
str +='        <a href="#"><span class="roundBox"><img src="../../public/image/common/ico24_fill/@2x/ico_24_light_filled.png" alt=""></span><p>가로등</p></a>';
str +='      </li>';
str +='      <li>';
str +='        <a href="#"><span class="roundBox"><img src="../../public/image/common/ico24_fill/@2x/ico_24_carehouse_filled.png" alt=""></span><p>세종관광두레</p></a>';
str +='      </li>';
str +='      <li>';
str +='        <a href="#"><span class="roundBox"><img src="../../public/image/common/ico24_fill/@2x/ico_24_management_filled.png" alt=""></span><p>여민전/상생플러스</p></a>';
str +='      </li>';
str +='      <li>';
str +='        <a href="#"><span class="roundBox"><img src="../../public/image/common/ico24_fill/@2x/ico_24_clinic_filled.png" alt=""></span><p>세종시명소</p></a>';
str +='      </li>';
str +='    </ul>';
str +='  </div>';
str +='  <div class="pcApp">';
str +='    <h3 class="pch3">이제, 앱으로 편하게 생활해요</h3>';
str +='    <div class="links">';
str +='      <a href="#" target="_blank"><img src="../../public/image/pc/ico_android.png" alt="안드로이드 앱" /></a>';
str +='      <a href="#" target="_blank"><img src="../../public/image/pc/ico_ios.png" alt="IOS 앱" /></a>';
str +='    </div>';
str +='  </div>';
str +='</div>';
str +='<div class="pcDeco poa1"></div>';
str +='<div class="pcDeco poa2"></div>';
str +='<div class="pcDeco poa3"></div>';
str +='<div class="pcDeco poa4"></div>';
str +='<div class="pcDeco poa5"></div>';
str +='<div class="pcDeco poa6"></div>';
str +='<div class="pcDeco poa7"></div>';
str +='<div class="pcDeco poa8"></div>';

document.write(str);
